# Generated by Django 3.0.5 on 2020-04-26 07:18

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
                ('object', users.models.UserManager()),
            ],
        ),
    ]
