# Generated by Django 3.0.5 on 2020-06-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200428_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='admins_avatars/default.png', null=True, upload_to='admins_avatars'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='customers_avatars/default.png', null=True, upload_to='customers_images'),
        ),
    ]
