# Generated by Django 3.0.5 on 2020-06-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products_images/default.png', upload_to='products_images'),
        ),
    ]
