# Generated by Django 3.0.5 on 2020-06-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200627_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products_images/default.png', upload_to='products_images'),
        ),
    ]
