# Generated by Django 3.0.5 on 2020-07-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20200701_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
