# Generated by Django 3.0.5 on 2020-07-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20200701_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
